// Copyright (c) WmiLightClassGenerator Contributors. Licensed under the MIT License.

namespace WmiLightClassGenerator.Generators;

using System.Management;
using WmiLightClassGenerator.Configuration;
using WmiLightClassGenerator.Metadata;

/// <summary>
/// Generates strongly-typed C# wrapper classes for WMI classes using WmiLight.
/// </summary>
public sealed class ClassGenerator
{
    private readonly string ns;
    private readonly Dictionary<string, string> propertyTypeOverrides;
    private readonly HashSet<string> stringEnumNames;
    private readonly Dictionary<string, string> referenceClassMappings;
    private readonly HashSet<string> warnedEmbeddedClassNames = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Initializes a new instance of the <see cref="ClassGenerator"/> class.
    /// </summary>
    /// <param name="ns">The C# namespace for generated classes.</param>
    /// <param name="propertyTypeOverrides">Maps WMI property names to enum type names.</param>
    /// <param name="stringEnumNames">Names of string-backed enums.</param>
    /// <param name="referenceClassMappings">Maps WMI reference class names to generated C# class names.</param>
    public ClassGenerator(
        string ns,
        Dictionary<string, string> propertyTypeOverrides,
        IEnumerable<string> stringEnumNames,
        Dictionary<string, string> referenceClassMappings)
    {
        this.ns = ns;
        this.propertyTypeOverrides = propertyTypeOverrides;
        this.stringEnumNames = new HashSet<string>(stringEnumNames);
        this.referenceClassMappings = referenceClassMappings;
    }

    /// <summary>
    /// Generates a complete C# source file for a WMI class wrapper.
    /// </summary>
    /// <param name="classMeta">The WMI class metadata.</param>
    /// <param name="className">The C# class name to generate.</param>
    /// <param name="classDef">The class definition from the configuration file.</param>
    /// <returns>The generated C# source code.</returns>
    public string Generate(WmiClassMetadata classMeta, string className, WmiClassDefinition classDef)
    {
        var w = new CodeWriter();
        WriteHeader(w, classMeta, className);
        w.BlankLine();
        w.Line($"namespace {this.ns};");
        w.BlankLine();
        w.Line("using System;");
        w.Line("using System.Collections.Generic;");
        w.Line("using System.Linq.Expressions;");
        w.Line("using WmiLight;");
        w.BlankLine();

        // A class uses "default optional" semantics when the config says so OR when
        // the WMI schema uses the Required qualifier (meaning absence of Required = optional).
        bool defaultOptional = classDef.DefaultOptional || classMeta.UsesRequiredQualifier;

        w.DocSummary($"Strongly-typed wrapper for the <c>{classMeta.WmiClassName}</c> WMI class in the <c>{CodeWriter.EscapeXml(classMeta.WmiNamespace)}</c> namespace.");
        w.Line($"public sealed class {className} : IDisposable");
        w.OpenBrace();

        WriteConstants(w, classMeta);
        w.BlankLine();
        WriteFields(w);
        w.BlankLine();
        WriteConstructors(w, className);
        w.BlankLine();
        WriteConnectionProperty(w, classMeta);
        w.BlankLine();
        WriteWmiObjectProperty(w);
        w.BlankLine();
        this.WriteProperties(w, classMeta);
        this.WriteMethods(w, classMeta, defaultOptional);
        this.WriteTypedMethodOverloads(w, classMeta, defaultOptional);
        WriteStaticHelpers(w, classMeta, className);
        WriteWhereMethod(w, className);
        WriteToEmbeddedInstanceXml(w);
        this.WriteBuilderClass(w, classMeta);
        WriteDispose(w);

        w.CloseBrace(); // class

        return w.ToString();
    }

    private static void WriteHeader(CodeWriter w, WmiClassMetadata classMeta, string className)
    {
        w.Line($"// <auto-generated>");
        w.Line($"//   Generated by WmiLightClassGenerator from {classMeta.WmiClassName}.");
        w.Line($"//   Do not edit manually.");
        w.Line($"// </auto-generated>");
        w.Line("#pragma warning disable");
    }

    private static void WriteConstants(CodeWriter w, WmiClassMetadata classMeta)
    {
        w.DocSummary("The WMI namespace for this class.");
        w.Line($"public const string WmiNamespace = @\"{classMeta.WmiNamespace}\";");
        w.BlankLine();
        w.DocSummary("The WMI class name.");
        w.Line($"public const string WmiClassName = \"{classMeta.WmiClassName}\";");
    }

    private static void WriteFields(CodeWriter w)
    {
        w.Line("internal readonly WmiConnection connection;");
        w.Line("private readonly WmiObject wmiObject;");
    }

    private static void WriteConstructors(CodeWriter w, string className)
    {
        w.DocSummary($"Initializes a new instance of the <see cref=\"{className}\"/> class wrapping an existing WMI object.");
        w.DocParam("connection", "The WMI connection used to query this instance.");
        w.DocParam("wmiObject", "The underlying WMI object.");
        w.Line($"public {className}(WmiConnection connection, WmiObject wmiObject)");
        w.OpenBrace();
        w.Line("this.connection = connection ?? throw new ArgumentNullException(nameof(connection));");
        w.Line("this.wmiObject = wmiObject ?? throw new ArgumentNullException(nameof(wmiObject));");
        w.CloseBrace();
    }

    private static void WriteConnectionProperty(CodeWriter w, WmiClassMetadata classMeta)
    {
        // Skip generating the Connection property if a WMI property named "Connection" exists
        bool hasConflict = classMeta.Properties.Any(p =>
            p.Name.Equals("Connection", StringComparison.OrdinalIgnoreCase));
        if (hasConflict)
        {
            return;
        }

        w.DocSummary("Gets the WMI connection used to query this instance.");
        w.Line("public WmiConnection Connection => this.connection;");
    }

    private static void WriteWmiObjectProperty(CodeWriter w)
    {
        w.DocSummary("Gets the underlying WMI object.");
        w.Line("public WmiObject WmiObject => this.wmiObject;");
    }

    private static void WriteStaticHelpers(CodeWriter w, WmiClassMetadata classMeta, string className)
    {
        w.BlankLine();

        // GetInstances
        w.DocSummary($"Queries all instances of <c>{classMeta.WmiClassName}</c>.");
        w.DocParam("connection", $"A WMI connection to the <c>{CodeWriter.EscapeXml(classMeta.WmiNamespace)}</c> namespace.");
        w.Line($"public static IEnumerable<{className}> GetInstances(WmiConnection connection)");
        w.OpenBrace();
        w.Line($"var query = new WmiQuery(connection, $\"SELECT * FROM {{WmiClassName}}\");");
        w.Line("using var enumerator = query.GetEnumerator();");
        w.Line("while (enumerator.MoveNext())");
        w.OpenBrace();
        w.Line($"yield return new {className}(connection, enumerator.Current);");
        w.CloseBrace();
        w.CloseBrace();

        w.BlankLine();

        // GetInstances with WHERE filter
        w.DocSummary($"Queries instances of <c>{classMeta.WmiClassName}</c> matching a WQL condition.");
        w.DocParam("connection", $"A WMI connection to the <c>{CodeWriter.EscapeXml(classMeta.WmiNamespace)}</c> namespace.");
        w.DocParam("condition", "A WQL WHERE condition (e.g. <c>\"Name='C:'\"</c>).");
        w.Line($"internal static IEnumerable<{className}> GetInstances(WmiConnection connection, string condition)");
        w.OpenBrace();
        w.Line($"var query = new WmiQuery(connection, $\"SELECT * FROM {{WmiClassName}} WHERE {{condition}}\");");
        w.Line("using var enumerator = query.GetEnumerator();");
        w.Line("while (enumerator.MoveNext())");
        w.OpenBrace();
        w.Line($"yield return new {className}(connection, enumerator.Current);");
        w.CloseBrace();
        w.CloseBrace();

        // GetByKey - only if we have key properties
        if (classMeta.KeyProperties.Count > 0)
        {
            w.BlankLine();
            WriteGetByKey(w, classMeta, className);
            w.BlankLine();
            WriteFromPath(w, classMeta, className);
        }
    }

    private static void WriteGetByKey(CodeWriter w, WmiClassMetadata classMeta, string className)
    {
        // Build key parameters
        var keyProps = classMeta.Properties
            .Where(p => p.IsKey)
            .ToList();

        var paramParts = keyProps
            .Select(p => $"{CimTypeMapper.ToCSharpType(p.CimType)} {ToCamelCase(p.Name)}")
            .ToList();

        paramParts.Insert(0, "WmiConnection connection");

        w.DocSummary($"Queries for a specific <c>{classMeta.WmiClassName}</c> instance by key.");
        w.Line($"public static {className}? GetByKey({string.Join(", ", paramParts)})");
        w.OpenBrace();

        // Build WHERE clause
        var conditions = keyProps
            .Select(p =>
            {
                string csharpType = CimTypeMapper.ToCSharpType(p.CimType);
                bool isString = csharpType == "string";
                return isString
                    ? $"{p.Name}='{{EscapeWql({ToCamelCase(p.Name)})}}'"
                    : $"{p.Name}={{{ToCamelCase(p.Name)}}}";
            })
            .ToList();

        string whereClause = string.Join(" AND ", conditions);
        w.Line($"var query = new WmiQuery(connection, $\"SELECT * FROM {{WmiClassName}} WHERE {whereClause}\");");
        w.Line("using var enumerator = query.GetEnumerator();");
        w.Line($"return enumerator.MoveNext() ? new {className}(connection, enumerator.Current) : null;");

        w.CloseBrace();

        // EscapeWql helper if we have string keys
        if (keyProps.Any(p => CimTypeMapper.ToCSharpType(p.CimType) == "string"))
        {
            w.BlankLine();
            w.Line("private static string EscapeWql(string value)");
            w.OpenBrace();
            w.Line("return value.Replace(\"'\", \"\\\\'\").Replace(\"\\\\\", \"\\\\\\\\\");");
            w.CloseBrace();
        }
    }

    private static void WriteFromPath(CodeWriter w, WmiClassMetadata classMeta, string className)
    {
        var keyProps = classMeta.Properties
            .Where(p => p.IsKey)
            .ToList();

        w.DocSummary($"Resolves a <c>{className}</c> instance from a WMI object path by extracting key property values.");
        w.DocParam("connection", "The WMI connection.");
        w.DocParam("wmiPath", "The WMI object path containing key property values.");
        w.DocReturns($"The resolved <c>{className}</c> instance, or <see langword=\"null\"/> if the path is empty or the instance is not found.");
        w.Line($"public static {className}? FromPath(WmiConnection connection, string wmiPath)");
        w.OpenBrace();
        w.Line("if (string.IsNullOrEmpty(wmiPath))");
        w.OpenBrace();
        w.Line("return null;");
        w.CloseBrace();
        w.BlankLine();

        // Extract each key value from the path and convert to the proper type
        foreach (var keyProp in keyProps)
        {
            string csharpType = CimTypeMapper.ToCSharpType(keyProp.CimType);
            string camelName = ToCamelCase(keyProp.Name);

            if (csharpType == "string")
            {
                w.Line($"string {camelName} = WmiPathParser.ExtractKeyValue(wmiPath, \"{keyProp.Name}\");");
            }
            else
            {
                w.Line($"{csharpType} {camelName} = {csharpType}.Parse(WmiPathParser.ExtractKeyValue(wmiPath, \"{keyProp.Name}\"));");
            }
        }

        // Call GetByKey
        string keyArgs = string.Join(", ", keyProps.Select(p => ToCamelCase(p.Name)));
        w.Line($"return GetByKey(connection, {keyArgs});");

        w.CloseBrace();
    }

    private static void WriteWhereMethod(CodeWriter w, string className)
    {
        w.BlankLine();
        w.DocSummary($"Queries instances of <c>{className}</c> matching a type-safe predicate.");
        w.DocParam("connection", "The WMI connection.");
        w.DocParam("predicate", "An expression that filters instances (translated to a WQL WHERE clause).");
        w.Line($"public static IEnumerable<{className}> Where(WmiConnection connection, Expression<Func<{className}, bool>> predicate)");
        w.OpenBrace();
        w.Line("string condition = WqlWhereVisitor.Translate(predicate);");
        w.Line("return GetInstances(connection, condition);");
        w.CloseBrace();
    }

    private static void WriteToEmbeddedInstanceXml(CodeWriter w)
    {
        w.BlankLine();
        w.DocSummary("Serializes this instance to WMI DTD 2.0 embedded instance XML.");
        w.DocReturns("A string containing the DTD 2.0 XML representation.");
        w.Line("public string ToEmbeddedInstanceXml()");
        w.Indent();
        w.Line("=> WmiDtdSerializer.Serialize(WmiClassName, this.wmiObject);");
        w.Outdent();
    }

    private static void WriteDispose(CodeWriter w)
    {
        w.BlankLine();
        w.Line("/// <inheritdoc/>");
        w.Line("public void Dispose() => this.wmiObject?.Dispose();");
    }

    /// <summary>
    /// WmiLight SetPropertyValue supports scalar types and string[].
    /// CimTypes that map to string (String, Reference, DateTime, Object) use string[] for arrays.
    /// For non-string array parameters (e.g. uint32[]), generate a TODO comment.
    /// Pure in-parameters (not in-out) are optional and wrapped in null-checks.
    /// </summary>
    private static void WriteSetParameter(CodeWriter w, string target, WmiParameterMetadata param, bool isOptional = false)
    {
        string camelName = ToCamelCase(param.Name);
        bool isValueType = CimTypeMapper.IsValueType(param.CimType) && !param.IsArray;

        // For optional parameters, access .Value for nullable value types
        string valueExpr = isOptional && isValueType ? $"{camelName}.Value" : camelName;

        if (param.IsArray && CimTypeMapper.ToCSharpType(param.CimType) != "string")
        {
            string innerComment = $"// TODO: WmiLight does not support SetPropertyValue for {CimTypeMapper.ToCSharpType(param.CimType, param.IsArray)}.";
            string innerSet = $"// {target}.SetPropertyValue(\"{param.Name}\", {valueExpr});";
            if (isOptional)
            {
                w.Line($"if ({camelName} is not null)");
                w.OpenBrace();
                w.Line(innerComment);
                w.Line(innerSet);
                w.CloseBrace();
            }
            else
            {
                w.Line(innerComment);
                w.Line(innerSet);
            }
        }
        else if (!param.IsArray && (param.CimType == System.Management.CimType.UInt64 || param.CimType == System.Management.CimType.SInt64))
        {
            // WMI COM stores uint64/sint64 as VT_BSTR — pass as string to avoid WBEM_E_TYPE_MISMATCH
            string line = $"{target}.SetPropertyValue(\"{param.Name}\", {valueExpr}.ToString(System.Globalization.CultureInfo.InvariantCulture));";
            WriteOptionalGuard(w, camelName, isOptional, isValueType, line);
        }
        else if (!param.IsArray && (param.CimType == System.Management.CimType.UInt32 || param.CimType == System.Management.CimType.UInt16 || param.CimType == System.Management.CimType.SInt16 || param.CimType == System.Management.CimType.UInt8 || param.CimType == System.Management.CimType.SInt8))
        {
            // WMI COM expects VT_I4 (32-bit signed integer) for unsigned 32-bit, 8-bit, and 16-bit values — cast to int to avoid WBEM_E_TYPE_MISMATCH
            string line = $"{target}.SetPropertyValue(\"{param.Name}\", (int){valueExpr});";
            WriteOptionalGuard(w, camelName, isOptional, isValueType, line);
        }
        else
        {
            string line = $"{target}.SetPropertyValue(\"{param.Name}\", {valueExpr});";
            WriteOptionalGuard(w, camelName, isOptional, isValueType, line);
        }
    }

    /// <summary>
    /// Writes a SetPropertyValue line, optionally wrapped in a null-check for optional parameters.
    /// </summary>
    private static void WriteOptionalGuard(CodeWriter w, string camelName, bool isOptional, bool isValueType, string innerLine)
    {
        if (!isOptional)
        {
            w.Line(innerLine);
            return;
        }

        string condition = isValueType ? $"{camelName}.HasValue" : $"{camelName} is not null";
        w.Line($"if ({condition})");
        w.OpenBrace();
        w.Line(innerLine);
        w.CloseBrace();
    }

    /// <summary>
    /// Determines whether a parameter is effectively optional.
    /// A parameter is optional when it has the <c>[Optional]</c> qualifier explicitly,
    /// OR when the class uses the <c>[Required]</c> qualifier convention (or config override)
    /// and this parameter does NOT have <c>[Required]</c>.
    /// </summary>
    private static bool IsEffectivelyOptional(WmiParameterMetadata param, bool defaultOptional)
    {
        if (param.IsOptional)
        {
            return true;
        }

        if (param.IsRequired)
        {
            return false;
        }

        return defaultOptional;
    }

    private static bool IsStringArrayType(WmiPropertyMetadata prop)
    {
        return prop.CimType == System.Management.CimType.String;
    }

    /// <summary>
    /// Writes a line to read an output parameter from the WMI result.
    /// For Reference types, uses non-generic GetPropertyValue with explicit cast.
    /// For Object types (embedded WMI objects), constructs the typed wrapper or WmiObject
    /// from the non-generic GetPropertyValue result.
    /// </summary>
    private static void WriteGetOutParameter(
        CodeWriter w,
        string paramName,
        string csharpType,
        System.Management.CimType cimType,
        bool isArray,
        string? wrapperClassName,
        string connRef)
    {
        string camelName = ToCamelCase(paramName);

        if (cimType == System.Management.CimType.Reference)
        {
            // Use non-generic GetPropertyValue with cast for Reference/Reference[] types
            w.Line($"{camelName} = ({csharpType})outResult.GetPropertyValue(\"{paramName}\");");
        }
        else if (cimType == System.Management.CimType.Object)
        {
            WriteGetOutParameterObject(w, paramName, camelName, csharpType, isArray, wrapperClassName, connRef);
        }
        else
        {
            w.Line($"{camelName} = outResult.GetPropertyValue<{csharpType}>(\"{paramName}\");");
        }
    }

    /// <summary>
    /// Writes code to read a CimType.Object output parameter.
    /// For known wrapper types, constructs the wrapper from the embedded WmiObject.
    /// For unknown types, casts to WmiObject directly.
    /// </summary>
    private static void WriteGetOutParameterObject(
        CodeWriter w,
        string paramName,
        string camelName,
        string csharpType,
        bool isArray,
        string? wrapperClassName,
        string connRef)
    {
        if (wrapperClassName is not null)
        {
            // Known wrapper type — construct from the embedded WmiObject
            string rawVar = $"raw{paramName}";
            w.OpenBrace();
            w.Line($"var {rawVar} = outResult.GetPropertyValue(\"{paramName}\");");

            if (isArray)
            {
                w.Line($"if ({rawVar} is WmiObject[] {camelName}Array)");
                w.OpenBrace();
                w.Line($"{camelName} = new {wrapperClassName}[{camelName}Array.Length];");
                w.Line($"for (int i = 0; i < {camelName}Array.Length; i++)");
                w.OpenBrace();
                w.Line($"{camelName}[i] = new {wrapperClassName}({connRef}, {camelName}Array[i]);");
                w.CloseBrace();
                w.CloseBrace();
                w.Line("else");
                w.OpenBrace();
                w.Line($"{camelName} = null;");
                w.CloseBrace();
            }
            else
            {
                w.Line($"if ({rawVar} is WmiObject {camelName}Obj)");
                w.OpenBrace();
                w.Line($"{camelName} = new {wrapperClassName}({connRef}, {camelName}Obj);");
                w.CloseBrace();
                w.Line("else");
                w.OpenBrace();
                w.Line($"{camelName} = null;");
                w.CloseBrace();
            }

            w.CloseBrace();
        }
        else
        {
            // Unknown embedded type — return as WmiObject
            w.Line($"{camelName} = outResult.GetPropertyValue(\"{paramName}\") as {csharpType};");
        }
    }

    /// <summary>
    /// For async methods with Reference output params, generates an ASSOCIATORS fallback
    /// that queries the completed job to find the affected element path when WmiLight
    /// does not populate the REF output parameter.
    /// </summary>
    private static void WriteAsyncRefFallback(CodeWriter w, WmiParameterMetadata param, string connRef)
    {
        string camelName = ToCamelCase(param.Name);
        w.BlankLine();
        w.Line($"if (string.IsNullOrEmpty({camelName}) && !string.IsNullOrEmpty(jobPath))");
        w.OpenBrace();
        w.Line($"{camelName} = WmiJobHelper.GetAffectedElementPath({connRef}, jobPath, \"{param.ReferenceClassName}\");");
        w.CloseBrace();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        // If all uppercase, lowercase everything
        if (name.All(c => char.IsUpper(c) || !char.IsLetter(c)))
        {
#pragma warning disable CA1308 // Normalize strings to uppercase - intentional lowercase for camelCase
            return name.ToLowerInvariant();
#pragma warning restore CA1308
        }

        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private void WriteInstanceMethodBody(
        CodeWriter w,
        WmiMethodMetadata method,
        WmiParameterMetadata? returnParam,
        List<WmiParameterMetadata> outParams,
        HashSet<string> inOutNames,
        bool hasAutoJobWait,
        bool defaultOptional)
    {
        bool hasInParams = method.InParameters.Count > 0;

        w.Line($"using var wmiMethod = this.wmiObject.GetMethod(\"{method.Name}\");");

        if (hasInParams)
        {
            w.Line("using var inParams = wmiMethod.CreateInParameters();");
            foreach (var inParam in method.InParameters)
            {
                bool isOptional = IsEffectivelyOptional(inParam, defaultOptional) && !inOutNames.Contains(inParam.Name);
                WriteSetParameter(w, "inParams", inParam, isOptional);
            }

            w.Line("this.wmiObject.ExecuteMethod(wmiMethod, inParams, out var outResult);");
        }
        else
        {
            w.Line("this.wmiObject.ExecuteMethod(wmiMethod, out var outResult);");
        }

        w.Line("using (outResult)");
        w.OpenBrace();

        if (hasAutoJobWait)
        {
            // Read ReturnValue and Job first, then wait for job completion
            string retType = CimTypeMapper.ToCSharpType(returnParam!.CimType, returnParam.IsArray);
            w.Line($"{retType} returnValue = outResult.GetPropertyValue<{retType}>(\"ReturnValue\");");
            w.Line("string jobPath = outResult.GetPropertyValue<string>(\"Job\");");
            w.Line("WmiJobHelper.WaitForJob(this.connection, returnValue, jobPath);");
        }

        // Assign ref (in/out) parameters from output
        foreach (var inParam in method.InParameters)
        {
            if (inOutNames.Contains(inParam.Name))
            {
                string paramType = CimTypeMapper.ToCSharpType(inParam.CimType, inParam.IsArray);
                WriteGetOutParameter(w, inParam.Name, paramType, inParam.CimType, inParam.IsArray, null, "this.connection");
                if (hasAutoJobWait && !inParam.IsArray && inParam.CimType == System.Management.CimType.Reference && inParam.ReferenceClassName is not null)
                {
                    WriteAsyncRefFallback(w, inParam, "this.connection");
                }
            }
        }

        // Assign pure out parameters
        foreach (var outParam in outParams)
        {
            string outType = this.ResolveOutputParamType(outParam);
            string? wrapperClass = this.GetObjectWrapperClassName(outParam);
            WriteGetOutParameter(w, outParam.Name, outType, outParam.CimType, outParam.IsArray, wrapperClass, "this.connection");
            if (hasAutoJobWait && !outParam.IsArray && outParam.CimType == System.Management.CimType.Reference && outParam.ReferenceClassName is not null)
            {
                WriteAsyncRefFallback(w, outParam, "this.connection");
            }
        }

        if (!hasAutoJobWait && returnParam is not null)
        {
            string retType = CimTypeMapper.ToCSharpType(returnParam.CimType, returnParam.IsArray);
            w.Line($"return outResult.GetPropertyValue<{retType}>(\"ReturnValue\");");
        }

        w.CloseBrace();
    }

    private void WriteStaticMethodBody(
        CodeWriter w,
        WmiMethodMetadata method,
        WmiParameterMetadata? returnParam,
        List<WmiParameterMetadata> outParams,
        HashSet<string> inOutNames,
        bool hasAutoJobWait,
        bool defaultOptional)
    {
        bool hasInParams = method.InParameters.Count > 0;

        w.Line("using var wmiClass = connection.GetClass(WmiClassName);");
        w.Line($"using var wmiMethod = wmiClass.GetMethod(\"{method.Name}\");");

        if (hasInParams)
        {
            w.Line("using var inParams = wmiMethod.CreateInParameters();");
            foreach (var inParam in method.InParameters)
            {
                bool isOptional = IsEffectivelyOptional(inParam, defaultOptional) && !inOutNames.Contains(inParam.Name);
                WriteSetParameter(w, "inParams", inParam, isOptional);
            }

            w.Line("connection.ExecuteMethod(wmiMethod, inParams, out var outResult);");
        }
        else
        {
            w.Line("connection.ExecuteMethod(wmiMethod, out var outResult);");
        }

        w.Line("using (outResult)");
        w.OpenBrace();

        if (hasAutoJobWait)
        {
            string retType = CimTypeMapper.ToCSharpType(returnParam!.CimType, returnParam.IsArray);
            w.Line($"{retType} returnValue = outResult.GetPropertyValue<{retType}>(\"ReturnValue\");");
            w.Line("string jobPath = outResult.GetPropertyValue<string>(\"Job\");");
            w.Line("WmiJobHelper.WaitForJob(connection, returnValue, jobPath);");
        }

        // Assign ref (in/out) parameters from output
        foreach (var inParam in method.InParameters)
        {
            if (inOutNames.Contains(inParam.Name))
            {
                string paramType = CimTypeMapper.ToCSharpType(inParam.CimType, inParam.IsArray);
                WriteGetOutParameter(w, inParam.Name, paramType, inParam.CimType, inParam.IsArray, null, "connection");
                if (hasAutoJobWait && !inParam.IsArray && inParam.CimType == System.Management.CimType.Reference && inParam.ReferenceClassName is not null)
                {
                    WriteAsyncRefFallback(w, inParam, "connection");
                }
            }
        }

        foreach (var outParam in outParams)
        {
            string outType = this.ResolveOutputParamType(outParam);
            string? wrapperClass = this.GetObjectWrapperClassName(outParam);
            WriteGetOutParameter(w, outParam.Name, outType, outParam.CimType, outParam.IsArray, wrapperClass, "connection");
            if (hasAutoJobWait && !outParam.IsArray && outParam.CimType == System.Management.CimType.Reference && outParam.ReferenceClassName is not null)
            {
                WriteAsyncRefFallback(w, outParam, "connection");
            }
        }

        if (!hasAutoJobWait && returnParam is not null)
        {
            string retType = CimTypeMapper.ToCSharpType(returnParam.CimType, returnParam.IsArray);
            w.Line($"return outResult.GetPropertyValue<{retType}>(\"ReturnValue\");");
        }

        w.CloseBrace();
    }

    private void WriteMethods(CodeWriter w, WmiClassMetadata classMeta, bool defaultOptional)
    {
        foreach (var method in classMeta.Methods)
        {
            w.BlankLine();
            this.WriteMethod(w, method, defaultOptional);
        }
    }

    private void WriteMethod(CodeWriter w, WmiMethodMetadata method, bool defaultOptional)
    {
        // Separate ReturnValue from other output params
        var returnParam = method.OutParameters.FirstOrDefault(p =>
            p.Name.Equals("ReturnValue", StringComparison.OrdinalIgnoreCase));
        var outOnlyParams = method.OutParameters
            .Where(p => !p.Name.Equals("ReturnValue", StringComparison.OrdinalIgnoreCase))
            .ToList();

        // Detect in/out parameters (appear in both InParameters and OutParameters)
        var inOutNames = new HashSet<string>(
            method.InParameters.Select(p => p.Name)
                .Intersect(outOnlyParams.Select(p => p.Name), StringComparer.OrdinalIgnoreCase),
            StringComparer.OrdinalIgnoreCase);

        // Detect auto-job-wait: method has an out param named "Job" of string/reference type
        var jobParam = outOnlyParams.FirstOrDefault(p =>
            p.Name.Equals("Job", StringComparison.OrdinalIgnoreCase)
            && (p.CimType == System.Management.CimType.String || p.CimType == System.Management.CimType.Reference)
            && !p.IsArray);
        bool hasAutoJobWait = jobParam is not null && returnParam is not null;

        // Pure out params are those not also in InParameters; exclude Job if auto-wait
        var pureOutParams = outOnlyParams
            .Where(p => !inOutNames.Contains(p.Name))
            .Where(p => !hasAutoJobWait || !p.Name.Equals("Job", StringComparison.OrdinalIgnoreCase))
            .ToList();

        // With auto-job-wait, return type becomes void (ReturnValue is consumed internally)
        string returnType;
        if (hasAutoJobWait)
        {
            returnType = "void";
        }
        else if (returnParam is not null)
        {
            returnType = CimTypeMapper.ToCSharpType(returnParam.CimType, returnParam.IsArray);
        }
        else
        {
            returnType = "void";
        }

        // Build parameter list
        // ref (in-out) and out params go first (required), then optional params (with defaults).
        var requiredParts = new List<string>();
        var optionalParts = new List<string>();
        foreach (var inParam in method.InParameters)
        {
            string paramType = CimTypeMapper.ToCSharpType(inParam.CimType, inParam.IsArray);
            if (inOutNames.Contains(inParam.Name))
            {
                requiredParts.Add($"ref {paramType} {ToCamelCase(inParam.Name)}");
            }
            else if (IsEffectivelyOptional(inParam, defaultOptional))
            {
                // Optional parameters use nullable types with null defaults.
                bool isValueType = CimTypeMapper.IsValueType(inParam.CimType) && !inParam.IsArray;
                string nullableType = isValueType ? $"{paramType}?" : paramType;
                optionalParts.Add($"{nullableType} {ToCamelCase(inParam.Name)} = null");
            }
            else
            {
                requiredParts.Add($"{paramType} {ToCamelCase(inParam.Name)}");
            }
        }

        foreach (var outParam in pureOutParams)
        {
            string paramType = this.ResolveOutputParamType(outParam);
            requiredParts.Add($"out {paramType} {ToCamelCase(outParam.Name)}");
        }

        // Required params first, then optional params (C# requires optional params at the end)
        var paramParts = new List<string>();
        paramParts.AddRange(requiredParts);
        paramParts.AddRange(optionalParts);

        string paramList = string.Join(", ", paramParts);

        // Write doc comment
        w.DocSummary(method.Description is not null
            ? CodeWriter.EscapeXml(method.Description)
            : $"Invokes the <c>{method.Name}</c> WMI method.");
        foreach (var inParam in method.InParameters)
        {
            w.DocParam(ToCamelCase(inParam.Name), inParam.Description is not null ? CodeWriter.EscapeXml(inParam.Description) : null);
        }

        foreach (var outParam in pureOutParams)
        {
            w.DocParam(ToCamelCase(outParam.Name), outParam.Description is not null ? CodeWriter.EscapeXml(outParam.Description) : null);
        }

        if (!hasAutoJobWait && returnParam is not null)
        {
            w.DocReturns("The WMI method return value.");
        }

        // Method signature
        if (method.IsStatic)
        {
            string staticParams = paramList.Length > 0
                ? $"WmiConnection connection, {paramList}"
                : "WmiConnection connection";
            w.Line($"public static {returnType} {method.Name}({staticParams})");
        }
        else
        {
            w.Line($"public {returnType} {method.Name}({paramList})");
        }

        w.OpenBrace();

        // Method body
        if (method.IsStatic)
        {
            this.WriteStaticMethodBody(w, method, returnParam, pureOutParams, inOutNames, hasAutoJobWait, defaultOptional);
        }
        else
        {
            this.WriteInstanceMethodBody(w, method, returnParam, pureOutParams, inOutNames, hasAutoJobWait, defaultOptional);
        }

        w.CloseBrace();
    }

    /// <summary>
    /// Resolves the C# type for an output parameter.
    /// For CimType.Object with a known EmbeddedClassName that maps to a generated wrapper class,
    /// returns the wrapper class name. Otherwise falls back to WmiObject or CimTypeMapper.
    /// </summary>
    private string ResolveOutputParamType(WmiParameterMetadata param)
    {
        if (param.CimType == System.Management.CimType.Object
            && param.EmbeddedClassName is not null
            && this.referenceClassMappings.TryGetValue(param.EmbeddedClassName, out string? wrapperClass))
        {
            return param.IsArray ? $"{wrapperClass}[]" : wrapperClass;
        }

        if (param.CimType == System.Management.CimType.Object)
        {
            if (param.EmbeddedClassName is not null
                && this.warnedEmbeddedClassNames.Add(param.EmbeddedClassName))
            {
                Console.Error.WriteLine(
                    $"  Warning: No wrapper class mapping for embedded class '{param.EmbeddedClassName}'. Falling back to WmiObject.");
            }

            return param.IsArray ? "WmiObject[]" : "WmiObject";
        }

        return CimTypeMapper.ToCSharpType(param.CimType, param.IsArray);
    }

    /// <summary>
    /// Gets the wrapper class name for a CimType.Object parameter, or null if none.
    /// </summary>
    private string? GetObjectWrapperClassName(WmiParameterMetadata param)
    {
        if (param.CimType == System.Management.CimType.Object
            && param.EmbeddedClassName is not null
            && this.referenceClassMappings.TryGetValue(param.EmbeddedClassName, out string? wrapperClass))
        {
            return wrapperClass;
        }

        return null;
    }

    private void WriteBuilderClass(CodeWriter w, WmiClassMetadata classMeta)
    {
        // Include all properties in the builder — even read-only ones can be set
        // when constructing embedded instance XML for method parameters.
        var allProps = classMeta.Properties;

        if (allProps.Count == 0)
        {
            return;
        }

        w.BlankLine();
        w.DocSummary("Fluent builder for creating embedded instance XML without magic strings.");
        w.Line("public sealed class Builder");
        w.OpenBrace();
        w.Line("private readonly WmiInstanceBuilder builder = new(WmiClassName);");

        foreach (var prop in allProps)
        {
            w.BlankLine();
            this.WriteBuilderMethod(w, prop);
        }

        w.BlankLine();
        w.DocSummary("Serializes the builder properties to WMI DTD 2.0 embedded instance XML.");
        w.DocReturns("A DTD 2.0 XML string representing the instance.");
        w.Line("public string ToEmbeddedInstanceXml() => this.builder.ToEmbeddedInstanceXml();");

        w.CloseBrace(); // Builder class

        w.BlankLine();
        w.DocSummary("Creates a new fluent builder for this WMI class.");
        w.Line("public static Builder Build() => new Builder();");
    }

    private void WriteBuilderMethod(CodeWriter w, WmiPropertyMetadata prop)
    {
        string csharpType = this.ResolvePropertyType(prop);
        bool isEnum = prop.EnumInfo is not null || this.propertyTypeOverrides.ContainsKey(prop.Name);
        bool isStringEnum = isEnum && this.IsStringEnumProperty(prop);
        string cimTypeStr = CimTypeMapper.ToCimTypeString(prop.CimType);
        string paramName = ToCamelCase(prop.Name);

        w.DocSummary($"Sets the <c>{prop.Name}</c> property.");
        w.Line($"public Builder {prop.Name}({csharpType} {paramName})");
        w.OpenBrace();

        if (isStringEnum)
        {
            w.Line($"this.builder.Set(\"{prop.Name}\", \"{cimTypeStr}\", {paramName}.ToWmiString());");
        }
        else if (isEnum && prop.IsArray)
        {
            string elementWmiType = CimTypeMapper.ToCSharpType(prop.CimType);
            w.Line($"this.builder.Set(\"{prop.Name}\", \"{cimTypeStr}\", Array.ConvertAll({paramName}, v => ({elementWmiType})v));");
        }
        else if (isEnum)
        {
            string wmiType = CimTypeMapper.ToCSharpType(prop.CimType);
            w.Line($"this.builder.Set(\"{prop.Name}\", \"{cimTypeStr}\", ({wmiType}){paramName});");
        }
        else
        {
            w.Line($"this.builder.Set(\"{prop.Name}\", \"{cimTypeStr}\", {paramName});");
        }

        w.Line("return this;");
        w.CloseBrace();
    }

    private void WriteTypedMethodOverloads(CodeWriter w, WmiClassMetadata classMeta, bool defaultOptional)
    {
        foreach (var method in classMeta.Methods)
        {
            this.WriteTypedMethodOverload(w, method, defaultOptional);
        }
    }

    private void WriteTypedMethodOverload(CodeWriter w, WmiMethodMetadata method, bool defaultOptional)
    {
        // Only generate typed overloads for methods with auto-job-wait
        // that have reference output parameters mappable to generated classes
        var returnParam = method.OutParameters.FirstOrDefault(p =>
            p.Name.Equals("ReturnValue", StringComparison.OrdinalIgnoreCase));
        var outOnlyParams = method.OutParameters
            .Where(p => !p.Name.Equals("ReturnValue", StringComparison.OrdinalIgnoreCase))
            .ToList();
        var inOutNames = new HashSet<string>(
            method.InParameters.Select(p => p.Name)
                .Intersect(outOnlyParams.Select(p => p.Name), StringComparer.OrdinalIgnoreCase),
            StringComparer.OrdinalIgnoreCase);

        var jobParam = outOnlyParams.FirstOrDefault(p =>
            p.Name.Equals("Job", StringComparison.OrdinalIgnoreCase)
            && (p.CimType == System.Management.CimType.String || p.CimType == System.Management.CimType.Reference)
            && !p.IsArray);
        bool hasAutoJobWait = jobParam is not null && returnParam is not null;

        if (!hasAutoJobWait)
        {
            return;
        }

        // Find reference out params (excluding Job) that map to generated classes
        var pureOutParams = outOnlyParams
            .Where(p => !inOutNames.Contains(p.Name))
            .Where(p => !p.Name.Equals("Job", StringComparison.OrdinalIgnoreCase))
            .ToList();

        // Find ref (in/out) params that are references
        var refParams = method.InParameters
            .Where(p => inOutNames.Contains(p.Name)
                && p.CimType == System.Management.CimType.Reference
                && p.ReferenceClassName is not null
                && this.referenceClassMappings.ContainsKey(p.ReferenceClassName))
            .ToList();

        // Find pure out params that are references
        var typedOutParams = pureOutParams
            .Where(p => p.CimType == System.Management.CimType.Reference
                && p.ReferenceClassName is not null
                && this.referenceClassMappings.ContainsKey(p.ReferenceClassName))
            .ToList();

        if (typedOutParams.Count == 0 && refParams.Count == 0)
        {
            return;
        }

        // Generate the typed overload
        w.BlankLine();

        // Build parameter list (same as original but without the typed out params — they become the return)
        var typedRequiredParts = new List<string>();
        var typedOptionalParts = new List<string>();
        foreach (var inParam in method.InParameters)
        {
            string paramType = CimTypeMapper.ToCSharpType(inParam.CimType, inParam.IsArray);

            // Skip ref params that we're converting to return values
            if (inOutNames.Contains(inParam.Name) && refParams.Any(p => p.Name == inParam.Name))
            {
                continue;
            }

            if (inOutNames.Contains(inParam.Name))
            {
                typedRequiredParts.Add($"ref {paramType} {ToCamelCase(inParam.Name)}");
            }
            else if (IsEffectivelyOptional(inParam, defaultOptional))
            {
                bool isValueType = CimTypeMapper.IsValueType(inParam.CimType) && !inParam.IsArray;
                string nullableType = isValueType ? $"{paramType}?" : paramType;
                typedOptionalParts.Add($"{nullableType} {ToCamelCase(inParam.Name)} = null");
            }
            else
            {
                typedRequiredParts.Add($"{paramType} {ToCamelCase(inParam.Name)}");
            }
        }

        // Include non-typed out params in the signature
        foreach (var outParam in pureOutParams)
        {
            if (typedOutParams.Any(p => p.Name == outParam.Name))
            {
                continue;
            }

            string paramType = this.ResolveOutputParamType(outParam);
            typedRequiredParts.Add($"out {paramType} {ToCamelCase(outParam.Name)}");
        }

        // Determine return type from typed params
        var allTypedParams = refParams.Concat(typedOutParams).ToList();
        string returnType;
        string returnClassName;
        bool returnsArray = false;

        if (allTypedParams.Count == 1)
        {
            var typedParam = allTypedParams[0];
            returnClassName = this.referenceClassMappings[typedParam.ReferenceClassName!];

            if (typedParam.IsArray)
            {
                returnType = $"{returnClassName}[]";
                returnsArray = true;
            }
            else
            {
                returnType = $"{returnClassName}?";
            }
        }
        else
        {
            // Multiple typed params — don't generate a typed overload for this case
            return;
        }

        var typedParamParts = new List<string>();
        typedParamParts.AddRange(typedRequiredParts);
        typedParamParts.AddRange(typedOptionalParts);
        string paramList = string.Join(", ", typedParamParts);

        // Write doc
        w.DocSummary(method.Description is not null
            ? CodeWriter.EscapeXml(method.Description)
            : $"Invokes the <c>{method.Name}</c> WMI method and returns the typed result.");
        w.DocReturns($"The resolved {returnClassName} instance, or <see langword=\"null\"/> if the path is empty.");

        if (method.IsStatic)
        {
            string staticParams = paramList.Length > 0
                ? $"WmiConnection connection, {paramList}"
                : "WmiConnection connection";
            w.Line($"public static {returnType} {method.Name}Typed({staticParams})");
        }
        else
        {
            w.Line($"public {returnType} {method.Name}Typed({paramList})");
        }

        w.OpenBrace();

        // Call the base method using named arguments to match the reordered signature
        // (required params including out come first, optional params come last).
        var callParams = new List<string>();
        foreach (var inParam in method.InParameters)
        {
            string camel = ToCamelCase(inParam.Name);
            if (inOutNames.Contains(inParam.Name) && refParams.Any(p => p.Name == inParam.Name))
            {
                // This ref param becomes the return — pass a local variable
                string paramType = CimTypeMapper.ToCSharpType(inParam.CimType, inParam.IsArray);
                w.Line($"{paramType} {camel} = default;");
                callParams.Add($"{camel}: ref {camel}");
            }
            else if (inOutNames.Contains(inParam.Name))
            {
                callParams.Add($"{camel}: ref {camel}");
            }
            else
            {
                callParams.Add($"{camel}: {camel}");
            }
        }

        foreach (var outParam in pureOutParams)
        {
            string camel = ToCamelCase(outParam.Name);
            if (typedOutParams.Any(p => p.Name == outParam.Name))
            {
                string paramType = this.ResolveOutputParamType(outParam);
                w.Line($"{paramType} {camel} = default;");
                callParams.Add($"{camel}: out {camel}");
            }
            else
            {
                callParams.Add($"{camel}: out {camel}");
            }
        }

        string callPrefix = method.IsStatic ? string.Empty : "this.";
        w.Line($"{callPrefix}{method.Name}({string.Join(", ", callParams)});");

        // Resolve the typed return
        var typedParam2 = allTypedParams[0];
        string localVar = ToCamelCase(typedParam2.Name);
        string resolvedClass = this.referenceClassMappings[typedParam2.ReferenceClassName!];

        if (returnsArray)
        {
            string connRef = method.IsStatic ? "connection" : "this.connection";
            w.Line($"if ({localVar} is null)");
            w.OpenBrace();
            w.Line($"return Array.Empty<{resolvedClass}>();");
            w.CloseBrace();
            w.BlankLine();
            w.Line($"var result = new {resolvedClass}[{localVar}.Length];");
            w.Line($"for (int i = 0; i < {localVar}.Length; i++)");
            w.OpenBrace();
            w.Line($"result[i] = {resolvedClass}.FromPath({connRef}, {localVar}[i]);");
            w.CloseBrace();
            w.BlankLine();
            w.Line("return result;");
        }
        else
        {
            string connRef = method.IsStatic ? "connection" : "this.connection";
            w.Line($"return {resolvedClass}.FromPath({connRef}, {localVar});");
        }

        w.CloseBrace();
    }

    private void WriteProperties(CodeWriter w, WmiClassMetadata classMeta)
    {
        foreach (var prop in classMeta.Properties)
        {
            w.BlankLine();
            this.WriteProperty(w, prop);
        }
    }

    private void WriteProperty(CodeWriter w, WmiPropertyMetadata prop)
    {
        string csharpType = this.ResolvePropertyType(prop);
        bool isEnum = prop.EnumInfo is not null || this.propertyTypeOverrides.ContainsKey(prop.Name);
        bool isStringEnum = isEnum && this.IsStringEnumProperty(prop);

        // WmiLight SetPropertyValue doesn't support non-string arrays — force read-only
        bool forceReadOnly = prop.IsArray && !IsStringArrayType(prop);

        w.DocSummary(prop.Description is not null
            ? CodeWriter.EscapeXml(prop.Description)
            : $"Gets{(prop.IsReadOnly || forceReadOnly ? string.Empty : " or sets")} the <c>{prop.Name}</c> property.");

        if (prop.IsReadOnly || forceReadOnly)
        {
            this.WriteReadOnlyProperty(w, prop, csharpType, isEnum, isStringEnum);
        }
        else
        {
            this.WriteReadWriteProperty(w, prop, csharpType, isEnum, isStringEnum);
        }
    }

    private void WriteReadOnlyProperty(
        CodeWriter w,
        WmiPropertyMetadata prop,
        string csharpType,
        bool isEnum,
        bool isStringEnum)
    {
        string wmiType = CimTypeMapper.ToCSharpType(prop.CimType, prop.IsArray);

        if (isStringEnum)
        {
            string enumName = this.ResolveEnumName(prop);
            w.Line($"public {enumName} {prop.Name}");
            w.Indent();
            w.Line($"=> this.wmiObject.GetPropertyValue<string>(\"{prop.Name}\").To{enumName}();");
            w.Outdent();
        }
        else if (isEnum && prop.IsArray)
        {
            // Array of enum values — need element-wise conversion
            string enumName = this.ResolveEnumName(prop);
            string elementWmiType = CimTypeMapper.ToCSharpType(prop.CimType, false);
            w.Line($"public {enumName}[] {prop.Name}");
            w.Indent();
            w.Line($"=> Array.ConvertAll(this.wmiObject.GetPropertyValue<{elementWmiType}[]>(\"{prop.Name}\"), v => ({enumName})v);");
            w.Outdent();
        }
        else if (isEnum)
        {
            string enumName = this.ResolveEnumName(prop);
            w.Line($"public {enumName} {prop.Name}");
            w.Indent();
            w.Line($"=> ({enumName})this.wmiObject.GetPropertyValue<{wmiType}>(\"{prop.Name}\");");
            w.Outdent();
        }
        else
        {
            w.Line($"public {csharpType} {prop.Name}");
            w.Indent();
            w.Line($"=> this.wmiObject.GetPropertyValue<{wmiType}>(\"{prop.Name}\");");
            w.Outdent();
        }
    }

    private void WriteReadWriteProperty(
        CodeWriter w,
        WmiPropertyMetadata prop,
        string csharpType,
        bool isEnum,
        bool isStringEnum)
    {
        string wmiType = CimTypeMapper.ToCSharpType(prop.CimType, prop.IsArray);

        if (isStringEnum)
        {
            string enumName = this.ResolveEnumName(prop);
            w.Line($"public {enumName} {prop.Name}");
            w.OpenBrace();
            w.Line($"get => this.wmiObject.GetPropertyValue<string>(\"{prop.Name}\").To{enumName}();");
            w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", value.ToWmiString());");
            w.CloseBrace();
        }
        else if (isEnum)
        {
            string enumName = this.ResolveEnumName(prop);
            w.Line($"public {enumName} {prop.Name}");
            w.OpenBrace();
            w.Line($"get => ({enumName})this.wmiObject.GetPropertyValue<{wmiType}>(\"{prop.Name}\");");

            // Apply the same WMI COM type-mismatch workarounds as WriteSetParameter
            if (prop.CimType is System.Management.CimType.UInt64 or System.Management.CimType.SInt64)
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", (({wmiType})value).ToString(System.Globalization.CultureInfo.InvariantCulture));");
            }
            else if (prop.CimType is System.Management.CimType.UInt32 or System.Management.CimType.UInt16 or System.Management.CimType.SInt16 or System.Management.CimType.UInt8 or System.Management.CimType.SInt8)
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", (int)({wmiType})value);");
            }
            else
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", ({wmiType})value);");
            }

            w.CloseBrace();
        }
        else
        {
            w.Line($"public {csharpType} {prop.Name}");
            w.OpenBrace();
            w.Line($"get => this.wmiObject.GetPropertyValue<{wmiType}>(\"{prop.Name}\");");

            // WMI COM type-mismatch workarounds — same as WriteSetParameter
            if (prop.CimType is System.Management.CimType.UInt64 or System.Management.CimType.SInt64)
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", value.ToString(System.Globalization.CultureInfo.InvariantCulture));");
            }
            else if (prop.CimType is System.Management.CimType.UInt32 or System.Management.CimType.UInt16 or System.Management.CimType.SInt16 or System.Management.CimType.UInt8 or System.Management.CimType.SInt8)
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", (int)value);");
            }
            else
            {
                w.Line($"set => this.wmiObject.SetPropertyValue(\"{prop.Name}\", value);");
            }

            w.CloseBrace();
        }
    }

    private string ResolvePropertyType(WmiPropertyMetadata prop)
    {
        // Check config overrides first
        if (this.propertyTypeOverrides.TryGetValue(prop.Name, out string? overrideType))
        {
            return overrideType;
        }

        // Check auto-discovered enums
        if (prop.EnumInfo is not null)
        {
            // Array enum properties return EnumType[]
            return prop.IsArray ? $"{prop.EnumInfo.EnumName}[]" : prop.EnumInfo.EnumName;
        }

        return CimTypeMapper.ToCSharpType(prop.CimType, prop.IsArray);
    }

    private string ResolveEnumName(WmiPropertyMetadata prop)
    {
        if (this.propertyTypeOverrides.TryGetValue(prop.Name, out string? overrideType))
        {
            return overrideType;
        }

        return prop.EnumInfo?.EnumName ?? prop.Name;
    }

    private bool IsStringEnumProperty(WmiPropertyMetadata prop)
    {
        if (this.propertyTypeOverrides.TryGetValue(prop.Name, out string? overrideType))
        {
            return this.stringEnumNames.Contains(overrideType);
        }

        return prop.EnumInfo?.IsStringBacked == true;
    }
}
