// Copyright (c) WmiLightClassGenerator Contributors. Licensed under the MIT License.

namespace WmiLightClassGenerator.Generators;

using WmiLightClassGenerator.Configuration;
using WmiLightClassGenerator.Metadata;

/// <summary>
/// Generates C# enum types from WMI ValueMap/Values qualifiers
/// and from config-defined string-backed enums.
/// </summary>
public sealed class EnumGenerator
{
    private readonly string ns;

    /// <summary>
    /// Initializes a new instance of the <see cref="EnumGenerator"/> class.
    /// </summary>
    /// <param name="ns">The C# namespace for generated enums.</param>
    public EnumGenerator(string ns)
    {
        this.ns = ns;
    }

    /// <summary>
    /// Generates an integer-backed enum from WMI ValueMap/Values qualifiers.
    /// </summary>
    /// <param name="enumMeta">The enum metadata.</param>
    /// <returns>The generated C# source code.</returns>
    public string Generate(WmiEnumMetadata enumMeta)
    {
        var w = new CodeWriter();
        WriteHeader(w);
        w.Line($"namespace {this.ns};");
        w.BlankLine();

        w.DocSummary(enumMeta.Description is not null
            ? CodeWriter.EscapeXml(enumMeta.Description)
            : $"Values for the <c>{enumMeta.EnumName}</c> WMI property.");

        string backingType = enumMeta.BackingType ?? "int";
        w.Line($"public enum {enumMeta.EnumName} : {backingType}");
        w.OpenBrace();

        int count = 0;
        foreach (var (memberName, value) in enumMeta.Values)
        {
            if (count > 0)
            {
                w.BlankLine();
            }

            w.DocSummary(memberName.Replace("_", " ", StringComparison.Ordinal));
            w.Line($"{memberName} = {value},");
            count++;
        }

        w.CloseBrace();
        return w.ToString();
    }

    /// <summary>
    /// Generates a string-backed enum with [WmiValue] attributes,
    /// plus converter extension methods.
    /// </summary>
    /// <param name="def">The string enum definition from configuration.</param>
    /// <returns>The generated C# source code.</returns>
    public string GenerateStringEnum(StringEnumDefinition def)
    {
        var meta = new WmiEnumMetadata
        {
            EnumName = def.Name,
            IsStringBacked = true,
            Description = def.Description,
            Values = def.Values,
        };
        return this.GenerateStringEnum(meta);
    }

    /// <summary>
    /// Generates a string-backed enum with [WmiValue] attributes,
    /// plus converter extension methods.
    /// </summary>
    /// <param name="enumMeta">The enum metadata.</param>
    /// <returns>The generated C# source code.</returns>
    public string GenerateStringEnum(WmiEnumMetadata enumMeta)
    {
        var w = new CodeWriter();
        WriteHeader(w);
        w.Line($"namespace {this.ns};");
        w.BlankLine();
        w.Line("using System;");
        w.BlankLine();

        // Enum definition
        w.DocSummary(enumMeta.Description is not null
            ? CodeWriter.EscapeXml(enumMeta.Description)
            : $"Values for the <c>{enumMeta.EnumName}</c> WMI property.");
        w.Line($"public enum {enumMeta.EnumName}");
        w.OpenBrace();

        int count = 0;
        foreach (var (memberName, wmiValue) in enumMeta.Values)
        {
            if (count > 0)
            {
                w.BlankLine();
            }

            w.DocSummary($"WMI value: <c>{CodeWriter.EscapeXml(wmiValue)}</c>.");
            w.Line($"[WmiValue(\"{EscapeCSharpString(wmiValue)}\")]");
            w.Line($"{memberName},");
            count++;
        }

        w.CloseBrace();
        w.BlankLine();

        // Extension methods for conversion
        WriteConverterExtensions(w, enumMeta);

        return w.ToString();
    }

    private static void WriteHeader(CodeWriter w)
    {
        w.Line("// <auto-generated />");
        w.Line("#pragma warning disable");
        w.BlankLine();
    }

    private static void WriteConverterExtensions(CodeWriter w, WmiEnumMetadata enumMeta)
    {
        string enumName = enumMeta.EnumName;

        w.DocSummary($"Extension methods for converting <see cref=\"{enumName}\"/> to and from WMI string values.");
        w.Line($"public static class {enumName}Extensions");
        w.OpenBrace();

        // ToWmiString
        w.DocSummary($"Converts a <see cref=\"{enumName}\"/> value to its WMI string representation.");
        w.Line($"public static string ToWmiString(this {enumName} value)");
        w.OpenBrace();
        w.Line("return value switch");
        w.OpenBrace();
        foreach (var (memberName, wmiValue) in enumMeta.Values)
        {
            w.Line($"{enumName}.{memberName} => \"{EscapeCSharpString(wmiValue)}\",");
        }

        w.Line($"_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),");
        w.CloseBrace(";");  // switch expression
        w.CloseBrace();  // method
        w.BlankLine();

        // Parse from string
        w.DocSummary($"Parses a WMI string value into a <see cref=\"{enumName}\"/>.");
        w.Line($"public static {enumName} To{enumName}(this string value)");
        w.OpenBrace();
        w.Line("return value switch");
        w.OpenBrace();
        foreach (var (memberName, wmiValue) in enumMeta.Values)
        {
            w.Line($"\"{EscapeCSharpString(wmiValue)}\" => {enumName}.{memberName},");
        }

        w.Line($"_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),");
        w.CloseBrace(";");  // switch expression
        w.CloseBrace();  // method

        w.CloseBrace();  // class
    }

    private static string EscapeCSharpString(string text)
    {
        return text
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);
    }
}