// Copyright (c) WmiLightClassGenerator Contributors. Licensed under the MIT License.

namespace WmiLightClassGenerator.Generators;

using System.Reflection;

/// <summary>
/// Emits infrastructure source files that generated code depends on.
/// Each file is stored as an embedded resource template with a <c>{0}</c> namespace placeholder.
/// </summary>
internal static class InfrastructureEmitter
{
    private const string Header =
        "// <auto-generated />\r\n" +
        "#pragma warning disable\r\n" +
        "\r\n";

    private static readonly string[] TemplateFileNames =
    [
        "WmiValueAttribute.cs",
        "WqlExpressionEvaluator.cs",
        "WqlWhereVisitor.cs",
        "WmiPathParser.cs",
        "WmiDtdSerializer.cs",
        "WmiInstanceBuilder.cs",
        "WmiJobHelper.cs",
        "KvpDataParser.cs",
    ];

    /// <summary>
    /// Emits all infrastructure files into the specified output directory.
    /// </summary>
    /// <param name="outputDir">The output directory for generated files.</param>
    /// <param name="ns">The C# namespace to use.</param>
    /// <param name="writeFile">A delegate that writes a file given (path, content).</param>
    public static void EmitAll(string outputDir, string ns, Action<string, string> writeFile)
    {
        var assembly = Assembly.GetExecutingAssembly();

        foreach (string fileName in TemplateFileNames)
        {
            string template = ReadTemplate(assembly, fileName);
            string content = Header + template.Replace("{0}", ns);
            string path = Path.Combine(outputDir, fileName);
            writeFile(path, content);
        }
    }

    private static string ReadTemplate(Assembly assembly, string fileName)
    {
        string resourceName = $"WmiLightClassGenerator.Templates.{fileName}";
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource not found: {resourceName}");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
